name: graineasy
description: Graineasy Mobile Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: 0.16.0
  loader_search_bar: ^1.0.2
  cupertino_icons: ^0.1.2
  flutter_range_slider: "^1.0.1"
  carousel_pro: ^0.0.13
  http: ^0.12.0+2
  localstorage: ^3.0.0
  connectivity: ^0.4.5+2
  shared_preferences: ^0.5.4+1
  url_launcher: ^5.2.5
  firebase_core: ^0.4.0
  cloud_firestore: ^0.12.0
  firebase_messaging: ^6.0.1
  json_serializable: ^3.2.3
  flutter_screenutil: ^0.6.0
  flushbar: ^1.5.3
  get_it: ^1.0.3+1
  provider: ^3.1.0+1
  cached_network_image: 1.1.3
  flutter_advanced_networkimage: any
  country_code_picker: ^1.1.7
  device_info: ^0.4.1+1
  flutter_share_me: ^0.4.0
  pull_to_refresh: ^1.5.7
  flutter_swiper: ^1.1.6
  file_picker: ^1.4.3+2
  path: ^1.6.4
  dio: ^3.0.7
  image_picker: ^0.6.1+4
  image_downloader: ^0.19.1
  jiffy: ^2.1.2
  path_provider: 1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
     - images/back.jpg
     - images/groceries.jpg
     - images/grtwo.jpg
     - images/grthre.jpg
     - images/veg.jpg
     - images/frozen.jpg
     - images/bev.jpg
     - images/brand_f.jpg
     - images/be.jpg
     - images/eggs.jpg
     - images/home.jpg
     - images/nonveg.jpg
     - images/apple.jpg
     - images/grapes.jpg
     - images/guava.jpg
     - images/kiwi.jpg
     - images/lemons.jpg
     - images/pineapple.jpg
     - images/tomato.jpg
     - images/gro.jpg
     - images/gelogo.png
     - images/user.png
     - images/manage.png
     - images/bargain.png
     - images/whatsapp.png
     - images/call.png
     - images/mail.png






     - assets/address.json
     - assets/items.json




  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
